# Makefile for basic code
#
# Author: Wang Long(wanglong@cse.buaa.edu.cn)
# Date: 2013-10-22 16:00:40 CST
#
#
objects := $(patsubst %.c,%.o,$(wildcard *.c))

all: $(objects)

	
.PHONY: clean
clean:
	@echo "Delete files"
	$(RM) *.o

